server.port=8081

# Database connection with environment variables and fallback to AWS RDS
# Local developers must set DB_URL, DB_USERNAME, and DB_PASSWORD env variables to connect locally.
spring.datasource.url=${DB_URL:jdbc:postgresql://hrms-backup.cxucu8ayu0hl.ap-south-1.rds.amazonaws.com:5432/postgres}
spring.datasource.username=hrmsbackup
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true