name: Hrms Build 

on:
  push:
    branches:
      - main

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          
      - name: Build Backend
        run: | 
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
           node-version: '20'
           cache: npm
           cache-dependency-path: hrms-frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: hrms-frontend
        run: npm ci

      - name: Build Frontend
        working-directory: hrms-frontend
        run: npm run build
